<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-12-16 06:23
=======
# Generated by Django 5.1.3 on 2024-12-17 16:20
>>>>>>> 49b9acdcbb373c37c908215009c43882f55a94c3

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=40, unique=True)),
<<<<<<< HEAD
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL)),
=======
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_auth_token', to=settings.AUTH_USER_MODEL)),
>>>>>>> 49b9acdcbb373c37c908215009c43882f55a94c3
            ],
        ),
    ]
